FROM python:3.13-slim

WORKDIR /app

ARG SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0

COPY pyproject.toml .
COPY src/ src/

RUN SETUPTOOLS_SCM_PRETEND_VERSION=${SETUPTOOLS_SCM_PRETEND_VERSION} pip install --no-cache-dir .

EXPOSE 8080

ENTRYPOINT ["esphome-mcp-web"]
